bigdatantue/Bigdata-Line-Bot

.gitignore, app.py, requirements.txt, vercel.json
1.設定基本echo bot程式
2.加入vercel.json設定檔
=> LINEBOTPJ-3 Base Case Bot程式

app.py, config.py
1.新增config.py 將基本設定另外拉出
2.使用singleton方式壁免重複建立實例
=> LINEBOTPJ-36 重構設定檔

app.py
=> LINEBOTPJ-29 加入好友訊息

api/spreadsheet.py, app.py, config.py, requirements.txt
1.新增套件pygsheets並新增google試算表API功能(spreadsheet.py)
2.新增user_info及ser_status工作表分別儲存使用者的資訊及使用者的狀態
3.在使用者加入好友時會初始化使用者的資訊到工作表
=> LINEBOTPJ-32 建立後台資料庫

api/spreadsheet.py, app.py
1. 在user_info工作表新增is_active的欄位
2. 在follow event中將is_active改成TRUE
3. 在新增的unfollow event中將is_active改成FALSE
- 加入好友及解除封鎖都會是TRUE
- 封鎖或刪除好友都會是FALSE
=> Linebotpj 38 記錄user是否為加入好友的狀態

api/firebase.py, config.py, requirements.txt
1.新增套件 firebase-admin==6.5.0
2.新增firebase.py可與firestore連線，並實作CRUD方法
=> LINEBOTPJ-39 連接FireStore資料庫

api/linebot_helper.py, api/spreadsheet.py, app.py, map.py, strategy.py, task.py, template.py
1. 新增template.py
1.1 class Template：抽象類別及方法必須實作execute()
1.2 class TemplateFactory：裡面有get_template()方法，可以回傳要執行的class
1.3 class Course:開課時間查詢的內容
2. 新增task.py
2.1 class Task：抽象類別及方法必須實作execute()
2.2 class TaskFactory：裡面有get_task()方法，可以回傳要執行的class
2.3 class Course:開課時間查詢的內容
4. 新增Strategy.py
3.1 class TemplateStrategy：處理使用者輸入功能的模板策略，再透過TemplateFactory找出要執行的class
3.2 class TaskStrategy：處理後續功能的任務策略，再透過TaskFactory找出要執行的class
5. app.py中的message event 和 postback event分別透過TemplateStrategy及TaskStrategy執行對應的功能
6. linebot_helper.py
5.1 新增class LineBotHelper：裡面的方法會是靜態方法並且為其他Helper也可能會用到的
5.1.1 將get_user_info()及reply_message()放入此類別
5.1.2 新增map_params()：用來取得flex message要替換的變數名稱對應要替換的值的字典
5.1.3 新增replace_variable()：用來替換掉字串中有{{}}的變數
5.1.4 將create_action()從RichMenuHelper抽出，只要有要創建Action物件就會用到
5.2 …
=> LINEBOTPJ-40 開課時間查詢

.gitignore, map.py, strategy.py, template.py
1.在template.py新增 class Certificate：當輸入"證書申請流程"，回覆Line Flex卡片
=> LINEBOTPJ-45 證書申請流程

map.py, strategy.py, task.py, template.py
1.在template.py新增 class Community：當輸入"社群學習資源"，回覆Line Flex卡片
2.在task.py新增 class Community：當點擊微課程按鈕時，回覆Line Flex卡片
=> LINEBOTPJ-47 社群學習資源

map.py, strategy.py, task.py, template.py
1.在template.py新增 class Counseling：當輸入"線上輔導+實體預約"，回覆Line Flex卡片 2.在task.py新增 class Counseling：當點擊"線上輔導" or "實體預約"按鈕時，回覆Line Flex卡片
=> LINEBOTPJ-48 線上輔導+實體預約

app.py, config.py, map.py, strategy.py, task.py, template.py
1. 在config.py新增feature的字典可以對應每項功能是否啟用
2. 在map.py定義class FeatureStatus(Enum) 把啟用狀態設為Enum(ENABLE 啟用、MAINTENANCE 維護中、DISABLE 未開放)，並把class EquipmentStatus(IntEnum)及功能名稱對應的英文拉出來
3. 在app.py判斷現在的功能啟用狀態給予不同回覆，並更改判斷temp邏輯，如果在A功能輸入文字的時候輸入其他功能的關鍵字，則回讓他跳出A功能，並把A功能的temp資料刪除
3. 實作主選單功能
=> LINEBOTPJ-51 功能啟用狀態

app.py, map.py, template.py
1. 新增Permission(IntEnum)定義權限
2. Template的預設權限都為1
3. 新增使用者的時候要多紀錄一筆Permission的值(預設1)
=> LINEBOTPJ-52 新增使用者權限

api/linebot_helper.py, app.py, map.py, task.py
1. 在linebot_helper.py新增multicfast_message及push_message
2. 租借人在設備租借申請時會傳送租借申請給Permisson>=3的user以供審核，並利用push_message回傳審核結果給租借人
3. 在map.py新增class EquipmentType(IntEnum):代表設備類型
=> LINEBOTPJ-53 器材借用 新增送出審核機制

map.py, task.py, template.py
1. 將所有firestore欄位根據功能名稱重構
2. 修正設備租借送出申請後無回覆送出申請提示
=> LINEBOTPJ-54 FireStore欄位重構

api/spreadsheet.py
1. 新增timestamp欄位在user_info工作表
2. 當使用者加入或封鎖好友時會記錄時間(在記錄使用者狀態(is_active)的同時新增)
=> LINEBOTPJ-56 記錄時間戳記欄位

api/firebase.py, task.py
1.新增filter_data的funtion，在firebase中直接篩選資料並提取
2.在task.py中找出有get_collection_data的部分，改成剛才新增的filter_data
=> LINEBOTPJ-64 更改FireStore查詢語法

templates/base.html, templates/notify/callback.html, templates/notify/error.html, templates/notify/register.html
1.做出連動頁面各情況相對應的HTML
2.為配合手機介面排版，調整文字呈現
=> LINEBOTPJ-66 設計Line Notify連動頁面

app.py
新增try except，當發生錯誤時傳送訊息請使用者聯絡系統管理員
=> LINEBOTPJ-77 處裡例外錯誤

app.py, requirements.txt
1.在linebot_helper.py新增show_loading_animation_()
2.requirements.txt 需將line-bot-sdk更新為3.11.1
=>  LINEBOTPJ-68 回覆訊息新增Loading Animation

app.py, requirements.txt
Reverts bigdatantue/Bigdata-Line-Bot#36
=> Revert " LINEBOTPJ-68 回覆訊息新增Loading Animation"

api/linebot_helper.py, app.py, requirements.txt
Reverts bigdatantue/Bigdata-Line-Bot#37
=> Revert "v1.1.0"

api/linebot_helper.py, app.py, requirements.txt
1.在linebot_helper.py新增show_loading_animation_()
2.requirements.txt 需將line-bot-sdk更新為3.11.1
=> LINEBOTPJ-68 回覆訊息新增Loading Animation

api/linebot_helper.py, api/spreadsheet.py, config.py, map.py, task.py, template.py
1. 完成知識測驗初步功能
2. 修正 replace_variable() 多一個參數max_count用來指定替換的最大數量(生成星星用)預設為0代表全部都會替換
3. 在spreadsheet.py新增update_cell_value()用來更新試算表儲存格
4. 在spreadsheet中需新增quiz放置大數據quiz的內容
5. 在spreadsheet中需新增quiz_record用來記錄測驗的答題狀況
6. 在spreadsheet中需新增quiz_log用來記錄測驗結過，在__generate_quiz_result中計算擊敗的人數比例(defeat_rate)
=> LINEBOTPJ-81 知識測驗

task.py
1. 題目的選項data多帶入{{quiz_id}}，用來檢驗是否為本次測驗
2. 修正結束後的重新挑戰，多帶入mode及category
=> LINEBOTPJ-88 使用者不可以重複作答

api/linebot_helper.py
1.在user_info新增了紀錄language和status_message的欄位
=> LINEBOTPJ-85 user_info紀錄使用者所有資訊

api/linebot_helper.py
1. 在函式reply_message內新增validate_reply的函式，並加上註解。
=> LINEBOTPJ-91 程式若在發送訊息時出錯不會顯示錯誤訊息

app.py
1.修復了切換圖文選單時會顯示loading_animation的bug
=> LINEBOTPJ-94 切換圖文選單會顯示等待動畫

tests/test_quiz.py
1. 新增tests資料夾裡面放入所有測試的py檔，檔名及方法必須以test_開頭
2. 新增產生問題及答案的line flex測試程式
=> LINEBOTPJ-96 知識測驗TestCase

task.py, tests/test_quiz.py
1. 新增generate_mask對名字進行遮罩
2. 修正test_quiz.py
3. 將歷史答題功能關掉
=> LINEBOTPJ-102 知識測驗 排行榜遮罩

api/spreadsheet.gs
1. 新增spreadsheet.gs，將程式備份，使用時須貼上在GAS
=> LINEBOTPJ-101 手動更新使用者資訊

Google Apps Script/Config.gs, Google Apps Script/LineMessagingAPI.gs
1.將原本在Config.gs底下進行更新使用者資訊的程式移到LineMessagingAPI底下
2.判斷ResponseCode為200時才進行欄位更新；若不為200則跳過
3.使用這資訊更新完成時會跳出視窗顯示已更新完成
=> Linebotpj 103 狀態為FALSE手動更新使用者資訊會把資料清空

api/linebot_helper.py, app.py, map.py
1.根據firebase-config-system底下的fixing是否為true，以此來判斷要不要暫停所有功能的運行
=> LINEBOTPJ-109 維修中提示

api/spreadsheet.py, app.py, config.py, liff_app.py, line_notify_app.py, map.py, template.py, templates/liff/liff.html, templates/liff/userinfo.html
1. cherry pick LINEBOTPJ-78
2. 修正get_row_index()，多判斷如果沒找到回傳None
3. 修正.replace('http', 'https')問題
4. 在template.py多取得設定個人資訊的頁面url，取代line flex的{{userinfo_url}}
5. 修正userinfo.html
6. 在liff_app.py多新增一個 /userinfo 的路由供表單post請求
=> LINEBOTPJ-110 設定個人資訊

app.py, map.py, task.py, template.py
1.在map.py中新增FAQ_SET，包含FAQ第一層Carousel的五個大分類
2.在app.py中判斷user_msg有沒有在map.py的FAQ_SET中，若有的話進入template.py
3.在template.py中新增class FAQ(template)，負責產生兩層Carousel的Bubbles
4.在task.py中新增class FAQ(Task)，負責回傳第二層Carousel問題的答案
5.在試算表中要新增faqs、faq_questions兩個工作表，詳情請見JIRA。
=> LINEBOTPJ-70 FAQ Code

api/linebot_helper.py
=> LINEBOTPJ-67 重構RichMenuHelper

app.py, config.py
1.在所有try-except的區塊新增Notify功能傳送通知
2.匯入traceback module獲取發生錯誤的程式檔案名稱和錯誤的行號
3.在.env中新增LINE_NOTIFY_GROUP_TOKEN，並由config.py讀取
=> LINEBOTPJ-107 發生錯誤時發送通知到群組

task.py
=> LINEBOTPJ-97 修正限時測驗結果

config.py
1. 啟用FAQ功能
2. 在check_env()中多判斷是否設定LINE_NOTIFY_GROUP_TOKEN
=> LINEBOTPJ-70 啟用FAQ功能

app.py, task.py
1. 在限時測驗中多添加一個規章同意選單
2. 更新限時測驗在取題目時，將題庫的內容與競賽專用的題庫的題目隨機分布
3. 添加判斷使用者有沒有填寫紀錄資料
4. 新增在限時測驗時，使用者有異常操作並且移除他參與競賽的權利
=> LINEBOTPJ-117 競賽規則

app.py
=> LINEBOTPJ-118 切換圖文選單出現等待動畫

task.py
1. 新增知識測驗中的歷史答題功能，包含「我的錯題」與「全服錯題」兩個選項。
2. 實現錯題的 carousel 顯示功能，根據正確率由低到高排序，每個選項最多顯示十題。
3. 限制題目文字長度為三行內，選項限制為一行，以確保 carousel 高度一致。
4. 為每道錯題新增「點擊查看更多」按鈕，點擊後可查看完整題目內容。
=> LINEBOTPJ-98 知識測驗 歷史答題

liff_app.py, task.py, template.py, templates/liff/rent.html
1.將表單邏輯整合至 LIFF
2.動態更新設備剩餘可借數量，確保用戶無法選擇超過可借數量的設備。
3.加入日期選擇的邏輯，借用日期不能早於今天，歸還日期不能早於借用日期。
4.修正日期輸入預設值問題，防止手機版本自動選擇今天的日期。
5.加入電話、email格式驗證
6.若使用者有設定個人資料，則自動帶入使用者基本資料
=> LINEBOTPJ-114 設備租借改使用表單

app.py, liff_app.py, map.py, task.py, template.py, templates/liff/userinfo.html
1.增加一個頁面為選擇查詢學期課程以及使用者本身的修課進度
2.在spreadsheet中填補缺失的課程，並且在user_details中新增一個verification的欄位作為驗證使用者身分的欄位
3.在app.py中新增使用者傳送圖片後發送通知到line_notify群組中
4.在使用者設定資料的liff表單中新增添加資料後送出後不可以修改的規則
5.在spreadsheet中新增一個user_courses_records的表用來儲存學生的修課紀錄資料
=> LINEBOTPJ-121 微學程修課進度查詢 Code

task.py
1. 先判斷指定類別是否有答題記錄，取代原本全域檢查整個檔案的方式。
2. 判斷邏輯改為檢查該類別的total_count是否有記錄。
=> LINEBOTPJ-125 歷史答題個人錯題報錯

app.py, config.py, liff_app.py
1. 新增環境變數LINE_GROUP_ID
2. 將錯誤訊息push到LINE_GROUP_ID的群組
=> LINEBOTPJ-123 發生錯誤通知改使用Messaging API

admin_app.py, app.py, config.py, features/equipment.py, features/quiz.py, features/setting.py, liff_app.py, map.py, templates/admin/index.html, templates/base.html, templates/http/unauthorized.html, templates/liff/userinfo.html
1. 在app中註冊一個新的admin_app負責admin介面的管理
2. 在template中新增admin.html
3. 新增admin_app負責管理admin的後端邏輯
4. 在base.html中新增boostrap的icon
5. 在user_info新增填寫yt資訊的欄位
=> LINEBOTPJ-129 新增設定YT後台

liff_app.py
=> LINEBOTPJ-131 將liff app改為動態路由

templates/admin/index.html
1. 修改index中的sort，把篩選的內容正確顯示出來
2. 設定防止內容為undefined的時候讓filter報錯
3. unauthorized修改成forbidden
=> LINEBOTPJ-130 修復後台查詢功能

static/css/admin/base.css, static/js/admin/base.js, templates/admin/base.html, templates/admin/index.html
=> LINEBOTPJ-132 後台會員儀表板

admin_app.py, api/linebot_helper.py, static/css/admin/base.css, static/css/admin/index.css, static/css/admin/line.css, static/css/admin/users.css, static/js/admin/base.js, static/js/admin/index.js, static/js/admin/line.js, static/js/admin/users.js, templates/admin/base.html, templates/admin/index.html, templates/admin/line.html, templates/admin/users.html
1. 重構templates/admin所有檔案
2. 將Richmenu設定集更新使用者資訊功能新增至後台操作
=> LINEBOTPJ-133 LINE後台管理操作

admin_app.py, api/firebase.py, static/css/admin/base.css, static/js/admin/base.js, static/js/admin/firebase.js, templates/admin/base.html, templates/admin/firebase.html
1. 修正fiebase.py取得資料多帶出document id
2. base.js實作auto complete下拉選單功能
3. admin_app.py新增處理firebase操作路由
=> LINEBOTPJ-136 Firebase後台操作
